services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672 # management
      - 5672:5672 # AMQP
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  postgres:
    image: postgres
    ports:
      - 1234:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=javacodechallengedb